// Static catalog data for car models, paints, wraps, wheels, and tunes

export const CAR_MODELS = [
  {
    id: "lambo_huracan",
    name: "Huracan EVO",
    brand: "Lamborghini",
    category: "supercar",
    baseStats: { speed: 88, acceleration: 92, handling: 85, braking: 87 },
    isPremium: false,
    description: "The quintessential V10 supercar — raw, visceral, and unapologetic.",
  },
  {
    id: "ferrari_sf90",
    name: "SF90 Stradale",
    brand: "Ferrari",
    category: "hypercar",
    baseStats: { speed: 95, acceleration: 96, handling: 90, braking: 92 },
    isPremium: true,
    description: "Ferrari's most powerful road car ever — 986hp of electrified fury.",
  },
  {
    id: "mclaren_720s",
    name: "720S",
    brand: "McLaren",
    category: "supercar",
    baseStats: { speed: 90, acceleration: 94, handling: 92, braking: 90 },
    isPremium: false,
    description: "Aerodynamic perfection wrapped in a carbon shell.",
  },
  {
    id: "bugatti_chiron",
    name: "Chiron Super Sport",
    brand: "Bugatti",
    category: "hypercar",
    baseStats: { speed: 99, acceleration: 98, handling: 88, braking: 94 },
    isPremium: true,
    description: "The fastest production car ever built — 1600hp of W16 excess.",
  },
  {
    id: "porsche_gt3",
    name: "911 GT3 RS",
    brand: "Porsche",
    category: "sports",
    baseStats: { speed: 82, acceleration: 84, handling: 97, braking: 96 },
    isPremium: false,
    description: "The purist's weapon — precision engineering over raw power.",
  },
  {
    id: "dodge_hellcat",
    name: "Challenger SRT Hellcat",
    brand: "Dodge",
    category: "muscle",
    baseStats: { speed: 86, acceleration: 90, handling: 70, braking: 78 },
    isPremium: false,
    description: "American muscle at its most extreme — 717hp of tire-shredding mayhem.",
  },
  {
    id: "nissan_gtr",
    name: "GT-R Nismo",
    brand: "Nissan",
    category: "sports",
    baseStats: { speed: 85, acceleration: 93, handling: 88, braking: 89 },
    isPremium: false,
    description: "Godzilla — the everyday supercar killer from Japan.",
  },
  {
    id: "toyota_gr86",
    name: "GR86 Drift Edition",
    brand: "Toyota",
    category: "drift",
    baseStats: { speed: 72, acceleration: 75, handling: 95, braking: 85 },
    isPremium: false,
    description: "Born on the touge — lightweight, balanced, and endlessly slideable.",
  },
];

export const PAINT_OPTIONS = [
  { id: "gloss_red", name: "Racing Red", hex: "#CC0000", finish: "gloss", isPremium: false },
  { id: "gloss_black", name: "Midnight Black", hex: "#0A0A0A", finish: "gloss", isPremium: false },
  { id: "gloss_white", name: "Arctic White", hex: "#F5F5F5", finish: "gloss", isPremium: false },
  { id: "gloss_blue", name: "Electric Blue", hex: "#0066FF", finish: "gloss", isPremium: false },
  { id: "gloss_yellow", name: "Lamborghini Yellow", hex: "#FFD700", finish: "gloss", isPremium: false },
  { id: "metallic_silver", name: "Silver Chrome", hex: "#C0C0C0", finish: "metallic", isPremium: false },
  { id: "metallic_gunmetal", name: "Gunmetal Grey", hex: "#2C3E50", finish: "metallic", isPremium: false },
  { id: "matte_black", name: "Stealth Black", hex: "#1A1A1A", finish: "matte", isPremium: false },
  { id: "matte_grey", name: "Military Grey", hex: "#4A4A4A", finish: "matte", isPremium: false },
  { id: "pearl_white", name: "Pearl White", hex: "#FFFFF0", finish: "pearl", isPremium: true },
  { id: "chrome_gold", name: "Gold Chrome", hex: "#FFD700", finish: "chrome", isPremium: true },
  { id: "satin_green", name: "British Racing Green", hex: "#004225", finish: "satin", isPremium: true },
  { id: "metallic_orange", name: "McLaren Orange", hex: "#FF6600", finish: "metallic", isPremium: true },
  { id: "gloss_purple", name: "Ultra Violet", hex: "#6B00CC", finish: "gloss", isPremium: true },
];

export const WRAP_OPTIONS = [
  { id: "solid_base", name: "Solid Base", pattern: "solid", primaryColor: "#CC0000", secondaryColor: null, isPremium: false },
  { id: "racing_stripes_white", name: "Racing Stripes", pattern: "racing_stripes", primaryColor: "#FFFFFF", secondaryColor: "#000000", isPremium: false },
  { id: "carbon_fiber_black", name: "Carbon Fiber", pattern: "carbon_fiber", primaryColor: "#1A1A1A", secondaryColor: "#333333", isPremium: false },
  { id: "camo_green", name: "Military Camo", pattern: "camo", primaryColor: "#4B5320", secondaryColor: "#8B7355", isPremium: false },
  { id: "flames_orange", name: "Hot Flames", pattern: "flames", primaryColor: "#FF4500", secondaryColor: "#FFD700", isPremium: true },
  { id: "geometric_blue", name: "Geo Pattern", pattern: "geometric", primaryColor: "#0066FF", secondaryColor: "#00FFFF", isPremium: true },
  { id: "marble_white", name: "Marble Luxe", pattern: "marble", primaryColor: "#F5F5F5", secondaryColor: "#888888", isPremium: true },
  { id: "gradient_sunset", name: "Sunset Gradient", pattern: "gradient", primaryColor: "#FF6B35", secondaryColor: "#8B00FF", isPremium: true },
];

export const WHEEL_OPTIONS = [
  { id: "spoke_silver", name: "Classic Spoke", style: "spoke", color: "#C0C0C0", isPremium: false },
  { id: "mesh_black", name: "Mesh Black", style: "mesh", color: "#1A1A1A", isPremium: false },
  { id: "split_spoke_gunmetal", name: "Split Spoke", style: "split_spoke", color: "#2C3E50", isPremium: false },
  { id: "multi_spoke_chrome", name: "Multi-Spoke Chrome", style: "multi_spoke", color: "#E8E8E8", isPremium: false },
  { id: "turbine_carbon", name: "Turbine Carbon", style: "turbine", color: "#0D0D0D", isPremium: true },
  { id: "forged_gold", name: "Forged Gold", style: "forged", color: "#FFD700", isPremium: true },
  { id: "deep_dish_red", name: "Deep Dish Red", style: "deep_dish", color: "#CC0000", isPremium: true },
];

export const TUNE_OPTIONS = [
  {
    id: "street_basic",
    name: "Street Tune",
    description: "Balanced street setup for everyday performance.",
    statBoosts: { speed: 0, acceleration: 2, handling: 2, braking: 1 },
    isPremium: false,
    tuneType: "street",
  },
  {
    id: "track_aggressive",
    name: "Track Attack",
    description: "Full track-day setup with stiffened suspension and race tyres.",
    statBoosts: { speed: 3, acceleration: 4, handling: 6, braking: 5 },
    isPremium: false,
    tuneType: "track",
  },
  {
    id: "drift_setup",
    name: "Drift King",
    description: "Rear-biased power delivery with loose, playful suspension.",
    statBoosts: { speed: 2, acceleration: 5, handling: -3, braking: 0 },
    isPremium: false,
    tuneType: "drift",
  },
  {
    id: "drag_strip",
    name: "Drag Spec",
    description: "Maximum launch and straight-line acceleration.",
    statBoosts: { speed: 5, acceleration: 8, handling: -5, braking: 2 },
    isPremium: true,
    tuneType: "drag",
  },
  {
    id: "rally_beast",
    name: "Rally Beast",
    description: "All-conditions grip with rally suspension tune.",
    statBoosts: { speed: 1, acceleration: 3, handling: 4, braking: 3 },
    isPremium: true,
    tuneType: "rally",
  },
  {
    id: "exotic_hypercar",
    name: "Hypercar Protocol",
    description: "Exotic-spec tune unlocking full performance potential.",
    statBoosts: { speed: 8, acceleration: 8, handling: 7, braking: 7 },
    isPremium: true,
    tuneType: "track",
  },
];

export const RACE_TRACKS = [
  { name: "Neon City Sprint", trackName: "neon_city", difficulty: "beginner", prizePoints: 50 },
  { name: "Desert Dash", trackName: "desert_highway", difficulty: "beginner", prizePoints: 75 },
  { name: "Mountain Pass", trackName: "mountain_pass", difficulty: "intermediate", prizePoints: 150 },
  { name: "Tokyo Underground", trackName: "tokyo_circuit", difficulty: "intermediate", prizePoints: 200 },
  { name: "Laguna Seca", trackName: "laguna_seca", difficulty: "advanced", prizePoints: 350 },
  { name: "Monaco Night Race", trackName: "monaco_night", difficulty: "advanced", prizePoints: 400 },
  { name: "Hypercar Invitational", trackName: "hypercar_circuit", difficulty: "elite", prizePoints: 750 },
  { name: "Nurburgring GP", trackName: "nurburgring", difficulty: "elite", prizePoints: 1000 },
];
